### PR TITLE
PR - Include Source generation script/Change domain

### PR DESCRIPTION
**Pull request by Arvinds-ds**
1. Include `observations.r` and observation.tests.r` generation scripts in `observations/src`
2. Change domain for data files and rst files to a new URL
3. .gitignore included `csv` file and it ignored the `datasets.csv` file which was required for generation

### CODE REVIEW

**Comment by dustinvtran** [comment]
Is this PR ready to review? Looks like it still stores all the rst files.

**Comment by Arvinds-ds** [comment]
My bad. Forgot to remove the doc folder. Pls see latest commit

**Comment by dustinvtran** [comment]
Looks great! One comment: Travis seems to take >30 minutes and is timing out, whereas in #20 it only took 12 minutes. In principle, the only change is the download server. Is this slowdown really because of the download?

**Comment by Arvinds-ds** [comment]
I noticed that. I think because Travis and Github are well integrated, it is fast. The flip side is that I was testing it locally when I was @ Columbia and it took < 200 secs and all tests passed. I am ssuming Travis has some restrictions on downloading data from external servers.

**Comment by Arvinds-ds** [comment]
Also I notice randon connection errors in the travis build log for e.g. affairs.py where as on my local machine it works..
image

Also, when I reran the tests again locally, it passed
image

**Comment by dustinvtran** [comment]
Got it. This sounds like a pervasive issue which is relevant to this PR but is more about #23 and how to handle Travis downloading many data sets. I propose merging the PR as is and leaving that issue open. Thoughts?

**Comment by Arvinds-ds** [comment]
Agree. For review purposes, Would request you to clone the repo and run tests locally and verify. It works at my end, but need you to validate it..

**Comment by dustinvtran** [comment]
Done!

**Pull request merged**
