### PR TITLE
Move observations.r generation script to src

### PR DESCRIPTION
**Pull request by Arvinds-ds**
The generation script: `gen_data_files.py`
The master csv file: `dataset.csv`
Test file generation in tmp directory : `test_script.sh`
Template file directory: `templates/`
rst files: `doc/`

### CODE REVIEW

**Comment by dustinvtran** [comment]
Thanks for the PR. It looks like the rst files are ~5MB, so before we merge this in it could be useful to finalize our ideas around where we'll store data. If we do successfully get a dedicated server, it could be useful to store the rst data there too. That way, we can avoid storing ~5MB both in the repo and in its commit history.

**Comment by dustinvtran** [comment]
On that note, it could be useful for now (if it's not much trouble) to assume we can download a folder of rst files from that github repo under some url. Do you know where in the code we'd make that specific change?

**Comment by Arvinds-ds** [comment]
That should be easy but where do we want to host the rst files? We can do a download and extract in `gen_data_files_from csv` as the first step

**Comment by dustinvtran** [comment]
As a temporary solution, I'm hosting all data at the url `http://dustintran.com/data/`, where two directories exist: `r/` and `r-docs/`. `r/` has the same structure as `csv_back/` in your repo; `r-docs/` has the same structure as `src/doc/` in your repo. For example, you can download `affairs.csv` from the url `http://dustintran.com/data/r/COUNT/affairs.csv`.

You can use this url to make your changes. Later when we set up a more permanent server, we'll basically just replace the top-level domain.

**Comment by Arvinds-ds** [comment]
What is the URL for rst files. I am unable to locate them is it `http://dustintran.com/data/r-docs/COUNT/rst/affairs.rst`

**Comment by Arvinds-ds** [comment]
When mirroring the file structure you have missed a file `CO2.csv` and unfortunately that has the same name as  another file `co2.csv` in the same package. You can include that file https://github.com/vincentarelbundock/Rdatasets/blob/master/csv/datasets/CO2.csv  (in your cloned location (say `co2_orig.csv`) and let me know. I will change the url in my master csv file.  Otherwise the tests pass.

**Comment by dustinvtran** [comment]
Ah, got it. This error is just due to me downloading everything on my Mac (which forgets about case sensitive file names) and then rsyncing them over to my Linux machine. You can now download it at the usual url `http://dustintran.com/r/data/datasets/CO2.csv` which is different than `.../co2.csv`.

> What is the URL for rst files. I am unable to locate them is it http://dustintran.com/data/r-docs/COUNT/rst/affairs.rst

My mistake: Following your naming it's currently `r-doc/`, e.g., `http://dustintran.com/data/r-doc/COUNT/rst/affairs.rst`.

**Comment by Arvinds-ds** [comment]
Kindly do the similar for rst `https://github.com/vincentarelbundock/Rdatasets/tree/master/doc/datasets/rst/CO2.rst`

**Comment by dustinvtran** [comment]
Done.

**Comment by Arvinds-ds** [comment]
Closing and reopening a new PR

**Pull request closed without merging**
